### ISSUE TITLE
There seems to be a conflict with a1111 sd webui tagcomplete

### ISSUE THREAD

**Issue by PuDood** [Haoming02/sd-webui-prompt-format#1]
<img width="786" alt="image" src="https://github.com/Haoming02/sd-webui-prompt-format/assets/127589252/939b5da9-9315-42f7-b738-1634b144c206">
When I enable your plugin but not use it (without checking Remove Duplicates)
When you click to generate an image, the tagcomplete plugin box will pop up

**Comment by Haoming02** [comment]
The issue seems to be solved since the above commit
I will close this now~
