### ISSUE TITLE
Allow exclusions to work with "Replace underscores with spaces on insertion"

### ISSUE THREAD

**Issue by MisterChief95** [Haoming02/sd-webui-prompt-format#10]
Would it be possible for the "Replace underscores with spaces on insertion" option to respect the exclusion list settings? Currently it will replace the tag's underscores with spaces on insertion even though they're in the underscore removal exclusion list.

**Comment by Haoming02** [comment]
> on insertion

wdym by this?

This extension only processes when you press the **Generate** *(or the `Manual  Format`)* button

**Comment by MisterChief95** [comment]
You're right, I got this extension mixed up with another. My bad! Closing this
