### ISSUE TITLE
Disable removing underscores from loras

### ISSUE THREAD

**Issue by slashedstar** [Haoming02/sd-webui-prompt-format#11]
With "remove underscores" enabled the extension removes underscores from loras so the second time you hit generate the loras aren't loaded

**Comment by Haoming02** [comment]
Phew~

Then yeah, if you added new Embedding/LoRA while the Webui is already running, go to **Settings** and find the `Prompt Format` section, then click on `Reload Cached Cards & Alias`. It will save all names containing `_` again.

*(or just `Reload UI`)*
