### ISSUE TITLE
Formatting out commas before line breaks

### ISSUE THREAD

**Issue by thaKnza** [Haoming02/sd-webui-prompt-format#12]
Hi! I love this extension, but it has a serious problem at least for my use case. Since my prompts get pretty long, I often format them with line breaks to help me see each part of the prompt. With this extension, if my prompt has a comma at the end of one part where there is a paragraph, it takes the comma out

For example

```
beautiful blue sky, sandy beach, fluffy clouds,

1girl, one piece bathing suit, happy, volleyball
```

becomes

```
beautiful blue sky, sandy beach, fluffy clouds

1girl, one piece bathing suit, happy, volleyball
```

At first I thought maybe this was purely aesthetic, but it does change the output (in my opinion for the worse) when the comma before a line break is removed.

It would be incredible if there was a way to disable this behavior!

**Comment by Haoming02** [comment]
ngl, I also encountered this issue from time to time XD

Added an option *(defaults to `enabled`)* that appends a comma at the end of a line, when there are multiple lines.

**Comment by thaKnza** [comment]
Based dev

**Comment by thaKnza** [comment]
I tested this and there is a problem. Now, commas appear on all line breaks. For example,

```beautiful blue sky, sandy beach, fluffy clouds,

1girl, one piece bathing suit, happy, volleyball```

Becomes

```beautiful blue sky, sandy beach, fluffy clouds,
,
1girl, one piece bathing suit, happy, volleyball```

**Comment by Haoming02** [comment]
Ah, good call

**Comment by thaKnza** [comment]
If we're looking at exceptions like BREAK, there is also ADDCOL, ADDCOM, ADDROW from regional prompter to consider lol

Do commas actually break this stuff, though? I'm not sure they do.
