### ISSUE TITLE
[Feature] Find duplicates for emphasis 

### ISSUE THREAD

**Issue by younyokel** [Haoming02/sd-webui-prompt-format#2]
Following doesn't get formatted:
```
line art, [line art], (line art)
```

**Comment by Haoming02** [comment]
Now it should correctly removes the duplicated words found in bracekets.
Though it will only keep the first *(left most)* instance of the word found.

**Comment by younyokel** [comment]
Thanks for quick fix!

> Though it will always keep the first _(left most)_ instance of the word found.

If it's possible, users might prefer to keep square brackets or prioritize parentheses using a simple radio button option in Settings, but i don't know how it will complicate the work. the option to exclude all words with emphasis might also be useful

**Comment by Haoming02** [comment]
> users might prefer to keep square brackets or prioritize parentheses
I'll see if I can implement this somehow.

> exclude all words with emphasis might also be useful
wdym by this?

You meant like ignore words in parentheses completely during formatting?

**Comment by younyokel** [comment]
> You meant like ignore words in parentheses completely during formatting?

I mean like an option that will make so that if there are duplicates `(word), word, [word]` it'll only leave the one without emphasiss: `word`

**Comment by Haoming02** [comment]
Ah, got it. I'll see what I can do.

I will close this issue in the meantime, as the original issue was indeed a bug and was fixed~
