### ISSUE TITLE
Notification: scheduled to be added to webui extension index if no objection is raised

### ISSUE THREAD

**Issue by w-e-w** [Haoming02/sd-webui-prompt-format#3]
Hi @Haoming02 I'm one of the maintenance of [webui extension Index](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
we received a request to add your extension to index, and we would like to confirm with you before adding it
see https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/173

scheduled to be added after a week if we did not receive any negative response from you

**Comment by Haoming02** [comment]
Sure! Thanks for including this Extension as well~

**Comment by w-e-w** [comment]
merged
